version: '3'

services:
  docker_node:
    image: docker_node
    build: 
        context: .
        dockerfile: ./docker/development/Dockerfile
    volumes: 
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000